apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: text-to-image-network-policy
  namespace: text-to-image-service
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: text-to-image-api
      ports:
        - port: 8080
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: text-to-image-service
      ports:
        - port: 8000
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              network.kubernetes.io/role: ingress
      ports:
        - port: 8000
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: llama-cpp-server
      ports:
        - port: 8080
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
