apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diffusion-model-cache-pvc
  namespace: text-to-image-service
  labels:
    app.kubernetes.io/name: text-to-image-api
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-pvc
  namespace: text-to-image-service
  labels:
    app.kubernetes.io/name: llama-cpp-server
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
