apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: text-to-image-api-pod-disruption-budget
  namespace: text-to-image-service
  labels:
    app.kubernetes.io/name: text-to-image-api
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: text-to-image-api
